[package]
name = "falco_plugin"
version = "0.1.0"
edition = "2021"

[[example]]
name = "source_plugin"
crate_type = ["dylib"]

[[example]]
name = "extract_plugin"
crate_type = ["dylib"]

[[example]]
name = "parse_plugin"
crate_type = ["dylib"]

[[example]]
name = "extract2_plugin"
crate_type = ["dylib"]

[[example]]
name = "async_plugin"
crate_type = ["dylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.56"
falco_event = { path = "../falco_event" }
falco_plugin_api = { path = "../falco_plugin_api" }
serde = "1.0.196"
serde_json = "1.0.113"
schemars = "0.8.16"
anyhow = "1.0.79"
memchr = "2.7.1"
log = { version = "0.4.21", features = ["std"] }
const_format = "0.2.32"
num-traits = "0.2.17"

# cargo install cargo-commander
# cargo run regen_bindings
[package.metadata.commands.regen_bindings.command]
cmd = [
    "wget https://raw.githubusercontent.com/falcosecurity/libs/master/userspace/plugin/plugin_types.h -O plugin/plugin_types.h",
    "wget https://raw.githubusercontent.com/falcosecurity/libs/master/userspace/plugin/plugin_api.h -O plugin/plugin_api.h",
    "bindgen plugin/plugin_api.h --no-debug 'ss_plugin_table_info|ss_plugin_table_fieldinfo' -- -I. > ../src/ffi.rs"]
working_dir = "api/"
